projects:
  - facebook/react-native
  - sindresorhus/execa
  - infinitered/gluegun
  - substack/minimist
  - AriaMinaei/pretty-error
  - ramda/ramda
  - skellock/ramdasauce
  - npm/node-semver
  - shelljs/shelljs
  - npm/node-which
  - avajs/ava
  - babel/babel-eslint
  - tschaub/mock-fs
  - vektra/mockery
  - istanbuljs/nyc
  - feross/standard
